name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2
      - name: Install python
        with:
          python-version: 3.10
      - name: Install deps
        run: |
          pip install poetry 
          make install
      - name: Run flake8 and pytest
        run: |
          make lint
          

